
version: 2

models:
  - name: stg_users
    description: ""
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_addresses
    description: ""
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: ""
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_order_items
    description: ""
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null
  - name: stg_products
    description: ""
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_promos
    description: ""
    columns:
      - name: promo_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_events
    description: ""
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          
